blank_issues_enabled: false
contact_links:
  - name: ğŸ› ï¸ æŠ€æœ¯é—®é¢˜å’¨è¯¢
    about: éœ€è¦æŠ€æœ¯æŒ‡å¯¼è¯·è”ç³»æ”¯æŒå›¢é˜Ÿ
    url: https://skiyee-ui.netlify.app/docs/getting-started/communication